name: Verify contents of a PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  tests:
    uses: ./.github/workflows/ci-tests.yaml
